[FIX/#250] 탐색 뷰 / QA 수정사항 반영
teamterning/Terning-Android pull request #252
Opened 2024-09-15 18:58 UTC by arinming

- closed #250 

## *⛳️ Work Description*
- task1
- task2
- task3

## *📸 Screenshot*

## *📢 To Reviewers*
- 현재 스크랩 다이얼로그 로직이 스크랩 '취소' 로직과는 다르게, Boolean 값을 인자로 전달받지 않더라구요. 그래서 scrap을 보냈는지 안 보냈는지 구분할 길이 없어서 홈 추천 공고, 검색 리스트 공고에서 스크랩 다이얼로그가 띄워졌다가 닫아지기만 해도 다시 해당 데이터들을 모두 불러와야한다는 이슈가 있었습니다.

따라서, ScrapDialog의 dismiss 함수에 Boolean 값을 전달받도록 수정하여 "스크랩" 했을 경우를 따지고 해당 인덱스만 UPDATE 되도록 수정하였습니다. 

제가 짠 로직이 적절할 지,.,. 로직 한 번만 확인해주세요!
만약 해당 로직이 채택된다면 효빈이도 스크랩 다이얼로그가 없어졌을 때 모든 데이터를 다시 받아오는 로직을 수정해야 할 것 같아용~! 

또한 이에 따라 캘린더 로직도 조금 수정하게 되었는데, 
석준오빠가 캘린더 수정한 피알 머지하고 컨플릭 해결한 뒤에 머지할게요 🙌🙌

2024-09-16 06:29 UTC, boiledEgg-s requested changes
고생하셨습니다!! 캘린더는 develop 풀 받고 수정해주세요~

2024-09-16 06:29 UTC, boiledEgg-s commented on feature/src/main/java/com/terning/feature/calendar/list/CalendarListScreen.kt
스크랩 다이얼로그의 로직은 문제가 없는데, 달력 화면의 구조가 많이 바뀌어서 충돌이 발생했네요,,
develop을 풀 받고 다시 수정해주셔야 할 것 같아요!!

현재 달력 화면들에선 ~Screen 컴포저블 안에서 다이얼로그를 호출하지 않고, 상위 컴포저블인 ~Route에서 Screen과 dialog를 각각 관리하고 있습니다! 따라서 바뀐 위치에 Boolean만 지정해주시면 될 것 같아요!

2024-09-16 06:29 UTC, boiledEgg-s commented on feature/src/main/java/com/terning/feature/calendar/week/CalendarWeekScreen.kt
위 댓글과 마찬가지입니당~

2024-09-17 08:26 UTC, Hyobeen-Park reviewed
boolean 추가하는거 좋은 생각인 것 같아요! 이거 머지 되고 나면 저도 수정 해볼게요!! 수고하셨습니다~~

2024-09-17 08:26 UTC, Hyobeen-Park commented on feature/src/main/java/com/terning/feature/search/search/component/ImageSlider.kt
> +                    pagerState.animateScrollToPage(nextPage)
애니메이션 넣은거 굿이에요~~!!

2024-09-17 08:26 UTC, Hyobeen-Park commented on core/src/main/java/com/terning/core/designsystem/component/bottomsheet/SortingBottomSheet.kt
> +    onSortChange: (Int) -> Unit = {},
오호!! 안그래도 이 바텀시트 수정 필요했었는데..!! 이거 활용해서 한번 홈 부분도 고쳐봐야겠네욤 수정 감사합니다!!ㅎㅎㅎㅎ

2024-09-18 12:38 UTC, boiledEgg-s approved these changes
개떡같이 설명해도 찰떡같이 알아듣고 수정하셨네요ㅎㅎ 너무 고생하셨습니당~

2024-09-19 04:01 UTC, merged